name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.10.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: programa

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: brunolaraujo
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker images
  # uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1
      uses: docker/build-push-action@v6.16.0
      with:
    # Build's context is the set of files located in the specified PATH or URL
        context: .
    # Path to the Dockerfile
        file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
        push: true
    # List of tags
        tags: brunolaraujo/10SOAT_TC03:${{ github.run_number}}